# Generated by Django 5.2.7 on 2025-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='street_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='street_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
