# Generated by Django 5.2.7 on 2025-10-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_apartment_number_voter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(default=''),
        ),
    ]
