# Generated by Django 5.2.5 on 2025-09-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_insta.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_insta.post')),
            ],
        ),
    ]
