# Generated by Django 5.2.5 on 2025-10-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_alter_profile_bio_text_alter_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
