# Generated by Django 5.2.5 on 2025-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0005_alter_photo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
