# Generated by Django 5.2.7 on 2025-11-25 20:06

from django.db import migrations, models


def populate_full_name(apps, schema_editor):
    Traveler = apps.get_model('project', 'Traveler')
    for traveler in Traveler.objects.all():
        first = getattr(traveler, 'first_name', '') or ''
        last = getattr(traveler, 'last_name', '') or ''
        full_name = f"{first} {last}".strip()
        traveler.full_name = full_name
        traveler.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_full_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='traveler',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='last_name',
        ),
    ]
